[package]
name = "cloud-storage"
version = "0.3.3"
authors = ["Luuk Wester <luuk.wester@gmail.com>"]
edition = "2018"
description = "A crate for uploading files to Google cloud storage, and for generating download urls."
license = "MIT"
repository = "https://github.com/ThouCheese/cloud-storage-rs"
documentation = "https://docs.rs/cloud-storage"
keywords = ["google", "cloud", "storage"]
readme = "README.md"
categories = ["api-bindings", "web-programming"]
maintenance = { status = "actively-developed" }

[dependencies]
reqwest = { version = "0.10.0", features = ["json", "blocking"] }
percent-encoding = "2"
url = "1"
jsonwebtoken = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.11"
lazy_static = "1"
dotenv = "0.15"
openssl = "0.10"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4"
