name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  GOOGLE_APPLICATION_CREDENTIALS: /auth.json

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create secret
      run: echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} > auth.json
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --features sync -- --test-threads=1
